jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            Pokemons:
                namespace_prefix: 'App\Domain\Entity'
                path: '%kernel.project_dir%/resources/config/serializer'

