framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\App\CommandHandler\CreatePokemonHandler': async
            'App\App\CommandHandler\UpdatePokemonHandler': async
            'App\App\CommandHandler\DeletePokemonHandler': async
            'App\App\QueryHandler\GetPokemonHandler': sync
            'App\App\QueryHandler\ListPokemonsHandler': sync
            'App\App\QueryHandler\ListTypesHandler': sync