framework:
    validation:
        enabled: true
        enable_annotations: false
        email_validation_mode: html5
        mapping:
            paths:
                - "%kernel.project_dir%/resources/config/validation/"
