App\Domain\Entity\Pokemon:
  properties:
    id:
      exclude: true
    createdAt:
      exclude: true
    updatedAt:
      exclude: true
    type1:
      type: string
      access_type: public_method
      accessor:
        getter: getType1Name
    type2:
      type: string
      access_type: public_method
      accessor:
        getter: getType2Name