App\Domain\Entity\Pokemon:
  attributes:
    
    createdAt:
      type: DateTime
    updatedAt:
      type: DateTime
    type1:
      type: string
      access_type: public_method
      accessor:
        getter: getType1Name
    type2:
      type: string
      access_type: public_method
      accessor:
        getter: getType2Name