App\Domain\Entity\User:
    type: entity
    table: public.user
    id:
      id:
        type: string
        # generator:
        #     strategy: CUSTOM
        # customIdGenerator:
        #     class: Symfony\Bridge\Doctrine\IdGenerator\UuidV4Generator
    fields:
      username:
        type: string
        unique: true
        length: 128
      password:
        type: string
        length: 128
      roles:
        type: json
