doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/resources/config/doctrine-mapping'
                prefix: App\Domain\Entity
