security:
    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Protect only the routes which modify the database
        pokemons:
            methods: [POST, PUT, PATCH, DELETE]
            pattern: ^/
            stateless: true
            jwt: ~

    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\User
                property: username

    password_hashers:
        App\Domain\Entity\User:
            algorithm: auto

    access_control:
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
